# ¿ES UN NÚMERO PRIMO?

# ESCIRBE UN PROGRAMA QUE SE ENCARGUE DE COMPROBAR SI UN NÚMERO ES O NO ES PRIMO
# HECHO ESTO, IMPRIME LOS NÚMEROS PRIMOS ENTRE 1 Y 100

# REALIZAMOS UN RANGO DE 1 A 100
for i in range(1,101,1):
    # USAMOS UN CONTADOR PARA SABER CUANTOS SON DIVISIBLES Y CADA VEZ QUE EMPIECE EL 
    # BUCLE REINICIAMOS EL CONTADOR
    cont=0
    # USAMOS OTRO BUCLE PARA QUE EMPIECE DESDE 1 HASTA EL NÚMERO DEL RANGO PRINCIPAL
    for x in range(1,i+1,1):
        # REALIZAMOS UNA CONDICIONAL DONDE SE VA DIVIENDIENDO 
        if i%x==0:
            # SI SE CUMPLE LA CONDICIÓN QUE SEA DIVISIBLE Y EL COCIENTE DE LA DIVISIÓN
            # SEA 0 SE AUMENTA EL CONTADOR
            cont+=1
    # REALIZAMOS UNA COMPROBACIÓN DEL CONTADOR, SI SOLO ES 2 QUE ES EL MISMO NÚMERO Y UNO
    # SE MUESTRA YA QUE ES PRIMO
    if cont==2:
        print(f"{i} ES PRIMO")